module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    colors: {
      'dark-blue': '#214151',
      'denim': '#187BC0',
      'dodger-blue': '#156ADA',
      'green-vogue': '#214151',
      'sand': '#9DB9E6',
      'gold': '#E6CA9D',
      'light-yellow': '#F8DC81',
      'green': '#A2D0C1',
      'sea-green': '#219653',
      'peach': '#DDF2DF',
      'yellow': '#F8DC81',
      'saffron': '#F4C839',
      'dim-grey': '#636363',
      'whisper': '#E5E5E5',
      'light-grey': '#FAFAFA',
      'trolley-grey': '#828282',
      'white-smoke': '#F2F2F2',
      'very-light-grey': '#CECECE',
      'gainsboro': '#E0E0E0',
      'silver': '#BDBDBD',
      'white': '#fff',
    },
    fontFamily: {
      sans: ['Open Sans','sans-serif'],
      serif: ['Merriweather', 'serif'],
    },
    extend: {},
  },
  plugins: [],
}
